### PR TITLE
add my super cool rate algorithm to the API

### PR DESCRIPTION
**Pull request by NullClock**
added a super cool new API (tell me if I did something wrong)

### CODE REVIEW

**Comment by radmanplays** [comment]
what is it exactly used for? can you show me a example?

**Comment by radmanplays** [comment]
@OtterCodes101 do you think we should add this?

**Comment by NullClock** [comment]
> what is it exactly used for? can you show me a example?

Honestly, it's not really that useful. Here's an example:
/rate me
I rate you a 69%
/rate firetruck
I rate firetruck a 96%

**Comment by OeildeLynx31** [comment]
> > what is it exactly used for? can you show me a example?
> 
> Honestly, it's not really that useful. Here's an example:
> /rate me
> I rate you a 69%
> /rate firetruck
> I rate firetruck a 96%

It is really not useful, nor helpful. Why should it be added? What is the advantage to add it?

**Comment by NullClock** [comment]
There's literally no advantage. I just added the feature cuz why not. I mean, the code's already done, there's no reason not to add it.

**Comment by radmanplays** [comment]
> > There's literally no advantage. I just added the feature cuz why not. I mean, the code's already done, there's no reason not to add it.
> 
> Why add a thing just to do nothing which is useful? A useless thing is... not useful to add.

I mean, why not add it? it's like saying: "oMG WhY DId yOU aDd modAPI.uwuify ?"
it's not like it's gonna make the game slower make the file size bigger. its not about it being useful, it's about it being fun

**Comment by OeildeLynx31** [comment]
> > > There's literally no advantage. I just added the feature cuz why not. I mean, the code's already done, there's no reason not to add it.
> > 
> > Why add a thing just to do nothing which is useful? A useless thing is... not useful to add.
> 
> I mean, why not add it? it's like saying: "oMG WhY DId yOU aDd modAPI.uwuify ?"
> it's not like it's gonna make the game slower make the file size bigger. its not about it being useful, it's about it being fun

I didn't understand I think, because he wants to add ModAPI.uwify? I thought that he added a program that would give a random rate to a random thing. I am confused, sorry. I don't really understand all if it is not that.

**Comment by radmanplays** [comment]
> > > > There's literally no advantage. I just added the feature cuz why not. I mean, the code's already done, there's no reason not to add it.
> > > 
> > > Why add a thing just to do nothing which is useful? A useless thing is... not useful to add.
> > 
> > I mean, why not add it? it's like saying: "oMG WhY DId yOU aDd modAPI.uwuify ?"
> > it's not like it's gonna make the game slower make the file size bigger. its not about it being useful, it's about it being fun
> 
> I didn't understand I think, because he wants to add ModAPI.uwify? I thought that he added a program that would give a random rate to a random thing. I am confused, sorry. I don't really understand all if it is not that.

no, I mean like it's kinda like ModAPI.uwuify which is just added for fun

**Comment by NullClock** [comment]
Alr. I just made it for fun. Instead of arguing let's just make a decision.
I think it should be added because this algorithm was kinda difficult to
make.

**Comment by Grant7777** [comment]
Why not turn this into a mod?

**Comment by NullClock** [comment]
Sure ig, but can mods access and patch the mod API? Or will I have to make
a custom API?

**Comment by ZXMushroom63** [comment]
> Sure ig, but can mods access and patch the mod API? Or will I have to make a custom API?
Patching the API and extending it with mods is very easy.

Here's a mod that adds the rate function to the Mod API:
```javascript
ModAPI.rate = (string) => {
            var hash = 0;
            var counterRate = 0;

            for (i = 0; i < string.length; i++) {
                hash = (hash << 5) - hash + string.codePointAt(i);
            }

            var res = (Math.abs(hash) % 100) + 1;

            return res;
}
```

**Review by Grant7777 — CHANGES_REQUESTED** [review]
Im writing this review because I didn't particularly appreciate how the conversation started.

1. I like the idea of rating other players, but I don't see any real use in pratice. You can turn it into a mod like I suggested in this [reply](https://github.com/eaglerforge/EaglerForge/pull/18#issuecomment-2094374155)
2. You put `counterRate` as a variable but never used it. Ima assume it was for something else.

Ya thats it.

**Comment by Grant7777** [comment]
The review was bad because I didn't have time. Maybe I'll give more details tomorrow :/

**Comment by stpv221** [comment]
This is a W feature and should be added immediately. It would be hella funny if like <br> 
/rate radmanplays <br>
I rate you 102%
/rate proofr <br>
lol hell no <br>

**Comment by stpv221** [comment]
you already know I'm adding this to OakAPI

**Comment by stpv221** [comment]
> > > > > There's literally no advantage. I just added the feature cuz why not. I mean, the code's already done, there's no reason not to add it.
> > > > 
> > > > 
> > > > Why add a thing just to do nothing which is useful? A useless thing is... not useful to add.
> > > 
> > > 
> > > I mean, why not add it? it's like saying: "oMG WhY DId yOU aDd modAPI.uwuify ?"
> > > it's not like it's gonna make the game slower make the file size bigger. its not about it being useful, it's about it being fun
> > 
> > 
> > I didn't understand I think, because he wants to add ModAPI.uwify? I thought that he added a program that would give a random rate to a random thing. I am confused, sorry. I don't really understand all if it is not that.
> 
> no, I mean like it's kinda like ModAPI.uwuify which is just added for fun

TBH if its fun, make it biased

**Comment by lax1dude** [comment]
Was `hash << 5` supposed to be an optimization for `hash * 31`, because doing `<< 5` is equivalent to `hash * 32`. I'm assuming you meant to multiply by `* 31` in the for loop because that's the same number Oracle's `java.lang.String.hashCode()` multiplies by.

**Comment by lax1dude** [comment]
OHH I get it, the whole expression is `(hash << 5) - hash`, which is the same as `hash * 31`. Nice.

**Comment by lax1dude** [comment]
Whatever performance increase you might get from that is overshadowed by unnecessarily calling `params.getString('string')` twice per character in the string, just call `params.getString('string')` once and store the return value in a local variable and use the local variable in the loop instead.

**Comment by cire3wastaken** [comment]
> i don't think we should add this

personally i would add this as an easter egg, kind of like how we added several silly features to resent as easter eggs

**Comment by NullClock** [comment]
lol I forgot about this

**Pull request merged**
